POST http://localhost:3000/register/
Content-Type: application/json

{
  "username": "adam_gilchrist",
  "name": "Adam Gilchrist",
  "password": "gilchrist_789",
  "gender": "male",
  "location": "Detroit"
}

###



POST http://localhost:3000/login/
Content-Type: application/json 

{
  "username": "adam_gilchrist",
  "password": "gilchrist_789"
}

###


PUT http://localhost:3000/change-password/
Content-Type: application/json 


{
  "username": "adam_gilchrist",
  "oldPassword": "gilchrist_789",
  "newPassword": "gilchrist@123"
}

###